<<<<<<< HEAD
# azure-pipelines.yml
name: Execucao-Manual

trigger: none  # Desativa CI automática (sem gatilhos de push)

pr: none       # Desativa CI em pull requests

# Habilita execução manual via botão "Run pipeline" no Azure DevOps
# (isso é automático se não houver triggers)

jobs:
- job: e2e_tests
  displayName: 'Executar Testes E2E Manualmente'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Checkout@1
    displayName: 'Clonar Repositório'

  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Instalar Node.js'

  - script: npm install -g yarn
    displayName: 'Instalar Yarn'

  - script: yarn
    displayName: 'Instalar Dependências'

  - script: yarn playwright install
    displayName: 'Instalar Playwright'

  - script: yarn run e2e
    displayName: 'Executar Testes E2E'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar Relatório HTML'
    inputs:
      PathtoPublish: 'playwright-report'
      ArtifactName: 'Relatorio-Testes'
=======
# CI de Nível 01 - Disparo manual a partir de 1 clique
# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:

# trabalhos / tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # máquina que vai rodar o job
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      # upload do relatório HTML
      - name: Upload de relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio Testes
          path: playwright-report/
>>>>>>> cc7cbe1e4ab2c46a8dc3db3ba85ce90afed5a8b7
