# CI de Nível 01 - Disparo manual a partir de 1 clique
name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executando Testes E2E com JSON
        run: |
          mkdir -p test-results
          npx playwright test --reporter=json > test-results/results.json

      - name: Publish Playwright test report
        uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: test-results/results.json
